// Generated by CoffeeScript 1.7.1
(function() {
  var TextDestroyerOfDoom, destroyer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  TextDestroyerOfDoom = (function() {
    function TextDestroyerOfDoom() {
      this.destroyText = __bind(this.destroyText, this);
    }

    TextDestroyerOfDoom.prototype.message = "Your text was destroyed!";

    TextDestroyerOfDoom.prototype.destroyText = function(i, element) {
      return $(element).text(this.message);
    };

    return TextDestroyerOfDoom;

  })();

  destroyer = new TextDestroyerOfDoom();

  $("div").each(destroyer.destroyText);

}).call(this);
