// Generated by CoffeeScript 1.7.1
(function() {
  var Car;

  Car = (function() {
    function Car() {}

    Car.prototype.speed = 10;

    Car.prototype.move = function(mph) {
      return this.speed += mph;
    };

    return Car;

  })();

  Car.prototype.getSpeed(function() {
    return this.speed;
  });

}).call(this);
